clone_depth: 1
version: '{branch}-{build}'
image: Visual Studio 2019
cache:
  - '%LOCALAPPDATA%\NuGet\v3-cache -> appveyor.yml'

dotnet_csproj:
  patch: true
  file: 'osu.Game\osu.Game.csproj' # Use wildcard when it's able to exclude Xamarin projects
  version: '0.0.{build}'

before_build:
  - cmd: dotnet --info # Useful when version mismatch between CI and local
  - cmd: nuget restore -verbosity quiet # Only nuget.exe knows both new (.NET Core) and old (Xamarin) projects

build:
  project: osu.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true

after_build:
  - cmd: dotnet tool restore

  # Temporarily disabled until the tool is upgraded to 5.0.
  # The version specified in .config/dotnet-tools.json (3.1.37601) won't run on .NET hosts >=5.0.7.
  # - cmd: dotnet format --dry-run --check

  - cmd: dotnet CodeFileSanity
  - cmd: dotnet jb inspectcode "osu.Desktop.slnf" --output="temp/inspectcodereport.xml" --caches-home="temp/inspectcode" --verbosity=WARN
  - cmd: dotnet nvika parsereport "temp/inspectcodereport.xml" --treatwarningsaserrors

test:
  assemblies:
    except:
      - '**\*Android*'
      - '**\*iOS*'
      - 'build\**\*'
