clone_depth: 1
version: '{build}'
image: Visual Studio 2019
test: off
skip_non_tags: true
configuration: Release
dotnet_csproj:
  patch: true
  file: 'osu.Game\osu.Game.csproj' # Use wildcard when it's able to exclude Xamarin projects
  version: $(APPVEYOR_REPO_TAG_NAME)
before_build:
  - ps: dotnet --info # Useful when version mismatch between CI and local
  - ps: nuget restore -verbosity quiet # Only nuget.exe knows both new (.NET Core) and old (Xamarin) projects
build:
  project: build\Desktop.proj # Skipping Xamarin Release that's slow and covered by fastlane
  parallel: true
  verbosity: minimal
  publish_nuget: true
after_build:
  - ps: dotnet remove osu.Game.Rulesets.Catch\osu.Game.Rulesets.Catch.csproj reference osu.Game\osu.Game.csproj
  - ps: dotnet add osu.Game.Rulesets.Catch\osu.Game.Rulesets.Catch.csproj package ppy.osu.Game -v $Env:APPVEYOR_REPO_TAG_NAME
  - ps: dotnet pack osu.Game.Rulesets.Catch\osu.Game.Rulesets.Catch.csproj /p:Version=$Env:APPVEYOR_REPO_TAG_NAME
deploy:
  - provider: Environment
    name: nuget
