on: [push, pull_request]
name: Continuous Integration

jobs:
  test:
    name: Test
    runs-on: ${{matrix.os.fullname}}
    env:
      OSU_EXECUTION_MODE: ${{matrix.threadingMode}}
    strategy:
       fail-fast: false
       matrix:
          os:
            - { prettyname: Linux, fullname: ubuntu-latest }
          threadingMode: ['SingleThread']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      # FIXME: libavformat is not included in Ubuntu. Let's fix that.
      # https://github.com/ppy/osu-framework/issues/4349
      # Remove this once https://github.com/actions/virtual-environments/issues/3306 has been resolved.
      - name: Install libavformat-dev
        if: ${{matrix.os.fullname == 'ubuntu-latest'}}
        run: |
         sudo apt-get update && \
         sudo apt-get -y install libavformat-dev

      - name: Install gdb
        run: |
          sudo apt-get update && \
          sudo apt-get -y install gdb

      - name: Compile
        run: dotnet build -c Debug -warnaserror osu.Desktop.slnf

      - name: Test
        run: ${{github.workspace}}/run-tests.sh ${{github.workspace}}/*.Tests/bin/Debug/*/*.Tests.dll --logger "trx;LogFileName=TestResults-${{matrix.os.prettyname}}-${{matrix.threadingMode}}.trx"

      - name: Upload Dump
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: deadlock
          path: deadlock.tar.bz2

      # Attempt to upload results even if test fails.
      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#always
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: osu-test-results-${{matrix.os.prettyname}}-${{matrix.threadingMode}}
          path: ${{github.workspace}}/TestResults/TestResults-${{matrix.os.prettyname}}-${{matrix.threadingMode}}.trx